import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import { ViewTransitions } from "next-view-transitions";
import { Toaster } from "sonner";
import AuthProvider from "@/lib/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Accueil - Evenlify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en">
        <body className={`${inter.className} scrollbar-hide`}>
          <AuthProvider>
            <Toaster richColors position={"top-right"} />
            {children}
          </AuthProvider>
        </body>
      </html>
    </ViewTransitions>
  );
}
